/* Bellwork exercise library — kettlebell + bodyweight */
window.BELLWORK_EXERCISES = [
  /* ——— Kettlebell hinge / posterior ——— */
  { id: "kb-swing", name: "Kettlebell Swing", equipment: ["kettlebell"], patterns: ["hinge"], muscles: ["glutes", "hamstrings", "back", "core"], level: "beginner", bells: 1, timed: false, defaultReps: 15, defaultSets: 5, rest: 45, cues: "Hinge, snap the hips, bell floats to chest height. Arms stay loose." },
  { id: "kb-2h-swing", name: "Two-Hand Swing", equipment: ["kettlebell"], patterns: ["hinge"], muscles: ["glutes", "hamstrings", "back", "core"], level: "beginner", bells: 1, timed: false, defaultReps: 20, defaultSets: 5, rest: 45, cues: "Same hinge as the swing; two hands on the horn." },
  { id: "kb-1h-swing", name: "One-Hand Swing", equipment: ["kettlebell"], patterns: ["hinge"], muscles: ["glutes", "hamstrings", "back", "core", "grip"], level: "intermediate", bells: 1, timed: false, defaultReps: 10, defaultSets: 6, rest: 40, cues: "Free hand tracks the working arm. Resist rotation." },
  { id: "kb-double-swing", name: "Double Kettlebell Swing", equipment: ["kettlebell"], patterns: ["hinge"], muscles: ["glutes", "hamstrings", "back", "core"], level: "advanced", bells: 2, timed: false, defaultReps: 12, defaultSets: 5, rest: 60, cues: "Two bells, one hinge. Keep them together through the arc." },
  { id: "kb-deadlift", name: "Kettlebell Deadlift", equipment: ["kettlebell"], patterns: ["hinge"], muscles: ["glutes", "hamstrings", "back"], level: "beginner", bells: 1, timed: false, defaultReps: 8, defaultSets: 4, rest: 60, cues: "Bell between the feet. Push the floor away, stand tall." },
  { id: "kb-sumo-dl", name: "Sumo Deadlift", equipment: ["kettlebell"], patterns: ["hinge"], muscles: ["glutes", "hamstrings", "adductors"], level: "beginner", bells: 1, timed: false, defaultReps: 10, defaultSets: 3, rest: 60, cues: "Wide stance, toes out, bell in the middle." },
  { id: "kb-single-leg-rdl", name: "Single-Leg RDL", equipment: ["kettlebell"], patterns: ["hinge"], muscles: ["hamstrings", "glutes", "core"], level: "intermediate", bells: 1, timed: false, defaultReps: 8, defaultSets: 3, rest: 45, cues: "Hinge on one leg. Keep hips square, soft knee." },
  { id: "kb-good-morning", name: "Kettlebell Good Morning", equipment: ["kettlebell"], patterns: ["hinge"], muscles: ["hamstrings", "back"], level: "intermediate", bells: 1, timed: false, defaultReps: 10, defaultSets: 3, rest: 45, cues: "Bell at the chest or behind the head. Long spine, hinge." },

  /* ——— Kettlebell squat ——— */
  { id: "kb-goblet-squat", name: "Goblet Squat", equipment: ["kettlebell"], patterns: ["squat"], muscles: ["quads", "glutes", "core"], level: "beginner", bells: 1, timed: false, defaultReps: 10, defaultSets: 4, rest: 60, cues: "Bell at the sternum. Elbows inside the knees at the bottom." },
  { id: "kb-front-squat", name: "Front Squat", equipment: ["kettlebell"], patterns: ["squat"], muscles: ["quads", "glutes", "core"], level: "intermediate", bells: 1, timed: false, defaultReps: 8, defaultSets: 4, rest: 75, cues: "Rack position. Elbows up, ribs down." },
  { id: "kb-double-front-squat", name: "Double Front Squat", equipment: ["kettlebell"], patterns: ["squat"], muscles: ["quads", "glutes", "core"], level: "advanced", bells: 2, timed: false, defaultReps: 6, defaultSets: 4, rest: 90, cues: "Two bells in rack. Stay stacked over midfoot." },
  { id: "kb-rack-squat", name: "Rack Squat", equipment: ["kettlebell"], patterns: ["squat"], muscles: ["quads", "glutes", "core"], level: "intermediate", bells: 1, timed: false, defaultReps: 8, defaultSets: 3, rest: 60, cues: "Single bell racked. Brace against the offset load." },
  { id: "kb-lunge", name: "Reverse Lunge", equipment: ["kettlebell"], patterns: ["lunge"], muscles: ["quads", "glutes"], level: "beginner", bells: 1, timed: false, defaultReps: 8, defaultSets: 3, rest: 45, cues: "Step back, both knees ~90°. Goblet or suitcase hold." },
  { id: "kb-forward-lunge", name: "Forward Lunge", equipment: ["kettlebell"], patterns: ["lunge"], muscles: ["quads", "glutes"], level: "intermediate", bells: 1, timed: false, defaultReps: 8, defaultSets: 3, rest: 45, cues: "Step forward under control. Don't crash the front knee." },
  { id: "kb-walking-lunge", name: "Walking Lunge", equipment: ["kettlebell"], patterns: ["lunge"], muscles: ["quads", "glutes"], level: "intermediate", bells: 1, timed: false, defaultReps: 12, defaultSets: 3, rest: 50, cues: "Continuous steps. Tall torso." },
  { id: "kb-cossack", name: "Cossack Squat", equipment: ["kettlebell"], patterns: ["squat"], muscles: ["adductors", "quads", "glutes"], level: "intermediate", bells: 1, timed: false, defaultReps: 6, defaultSets: 3, rest: 45, cues: "Shift side to side. Heel of the bent leg stays down if you can." },

  /* ——— Kettlebell push / press ——— */
  { id: "kb-press", name: "Overhead Press", equipment: ["kettlebell"], patterns: ["push"], muscles: ["shoulders", "triceps", "core"], level: "intermediate", bells: 1, timed: false, defaultReps: 6, defaultSets: 4, rest: 75, cues: "From rack, press in a slight arc. Finish with biceps by the ear." },
  { id: "kb-push-press", name: "Push Press", equipment: ["kettlebell"], patterns: ["push"], muscles: ["shoulders", "triceps", "legs"], level: "intermediate", bells: 1, timed: false, defaultReps: 8, defaultSets: 4, rest: 60, cues: "Dip and drive with the legs, then punch the bell up." },
  { id: "kb-double-press", name: "Double Press", equipment: ["kettlebell"], patterns: ["push"], muscles: ["shoulders", "triceps", "core"], level: "advanced", bells: 2, timed: false, defaultReps: 5, defaultSets: 4, rest: 90, cues: "Two bells from rack. Keep the ribs down." },
  { id: "kb-bottoms-up-press", name: "Bottoms-Up Press", equipment: ["kettlebell"], patterns: ["push"], muscles: ["shoulders", "forearms", "core"], level: "advanced", bells: 1, timed: false, defaultReps: 5, defaultSets: 3, rest: 60, cues: "Bell upside down. Crush the handle and move slowly." },
  { id: "kb-floor-press", name: "Floor Press", equipment: ["kettlebell"], patterns: ["push"], muscles: ["chest", "triceps", "shoulders"], level: "beginner", bells: 1, timed: false, defaultReps: 8, defaultSets: 3, rest: 60, cues: "Lie on the floor, press from the racked arm. Pause at the bottom." },
  { id: "kb-tgu", name: "Turkish Get-Up", equipment: ["kettlebell"], patterns: ["skill", "core"], muscles: ["shoulders", "core", "hips"], level: "intermediate", bells: 1, timed: false, defaultReps: 3, defaultSets: 3, rest: 60, cues: "Slow, segmented stand-up with eyes on the bell. Reverse the same path." },
  { id: "kb-windmill", name: "Windmill", equipment: ["kettlebell"], patterns: ["skill", "core"], muscles: ["obliques", "shoulders", "hamstrings"], level: "advanced", bells: 1, timed: false, defaultReps: 5, defaultSets: 3, rest: 60, cues: "Bell locked overhead. Hinge and rotate, hand traces the leg." },

  /* ——— Kettlebell pull / clean / carry ——— */
  { id: "kb-clean", name: "Kettlebell Clean", equipment: ["kettlebell"], patterns: ["pull"], muscles: ["back", "glutes", "grip"], level: "intermediate", bells: 1, timed: false, defaultReps: 8, defaultSets: 4, rest: 45, cues: "Hike, then zip the bell into the rack. Don't corkscrew the wrist." },
  { id: "kb-double-clean", name: "Double Clean", equipment: ["kettlebell"], patterns: ["pull"], muscles: ["back", "glutes", "grip"], level: "advanced", bells: 2, timed: false, defaultReps: 6, defaultSets: 4, rest: 75, cues: "Both bells into rack together. Soft landing on the forearms." },
  { id: "kb-snatch", name: "Kettlebell Snatch", equipment: ["kettlebell"], patterns: ["pull", "hinge"], muscles: ["glutes", "back", "shoulders", "grip"], level: "advanced", bells: 1, timed: false, defaultReps: 8, defaultSets: 6, rest: 60, cues: "Punch through at the top. Bell rolls over the hand, not slaps it." },
  { id: "kb-high-pull", name: "High Pull", equipment: ["kettlebell"], patterns: ["pull"], muscles: ["back", "shoulders", "glutes"], level: "intermediate", bells: 1, timed: false, defaultReps: 10, defaultSets: 4, rest: 45, cues: "Swing path, then pull the elbow high and back." },
  { id: "kb-row", name: "Kettlebell Row", equipment: ["kettlebell"], patterns: ["pull"], muscles: ["back", "biceps"], level: "beginner", bells: 1, timed: false, defaultReps: 10, defaultSets: 3, rest: 45, cues: "Hinge stance. Pull the elbow to the hip." },
  { id: "kb-renegade-row", name: "Renegade Row", equipment: ["kettlebell"], patterns: ["pull", "core"], muscles: ["back", "core"], level: "advanced", bells: 2, timed: false, defaultReps: 8, defaultSets: 3, rest: 60, cues: "Plank on two bells. Row one, hips stay quiet." },
  { id: "kb-farmer-carry", name: "Farmer Carry", equipment: ["kettlebell"], patterns: ["carry"], muscles: ["grip", "core", "traps"], level: "beginner", bells: 2, timed: true, defaultReps: 40, defaultSets: 3, rest: 45, cues: "Tall walk. Don't lean or shrug." },
  { id: "kb-suitcase-carry", name: "Suitcase Carry", equipment: ["kettlebell"], patterns: ["carry"], muscles: ["obliques", "grip"], level: "beginner", bells: 1, timed: true, defaultReps: 30, defaultSets: 4, rest: 40, cues: "One-sided carry. Don't side-bend toward the bell." },
  { id: "kb-rack-carry", name: "Rack Carry", equipment: ["kettlebell"], patterns: ["carry"], muscles: ["core", "shoulders"], level: "intermediate", bells: 1, timed: true, defaultReps: 30, defaultSets: 3, rest: 40, cues: "Bell in rack, walk. Keep the elbow in." },
  { id: "kb-oh-carry", name: "Overhead Carry", equipment: ["kettlebell"], patterns: ["carry"], muscles: ["shoulders", "core"], level: "advanced", bells: 1, timed: true, defaultReps: 20, defaultSets: 3, rest: 45, cues: "Arm locked, biceps by the ear. Short steps." },

  /* ——— Kettlebell combos ——— */
  { id: "kb-thruster", name: "Thruster", equipment: ["kettlebell"], patterns: ["squat", "push"], muscles: ["quads", "shoulders", "core"], level: "intermediate", bells: 1, timed: false, defaultReps: 8, defaultSets: 4, rest: 60, cues: "Front squat into an immediate press." },
  { id: "kb-clean-press", name: "Clean & Press", equipment: ["kettlebell"], patterns: ["pull", "push"], muscles: ["full body"], level: "intermediate", bells: 1, timed: false, defaultReps: 6, defaultSets: 4, rest: 75, cues: "Clean to rack, pause, press." },
  { id: "kb-clean-squat", name: "Clean + Front Squat", equipment: ["kettlebell"], patterns: ["pull", "squat"], muscles: ["full body"], level: "intermediate", bells: 1, timed: false, defaultReps: 6, defaultSets: 4, rest: 75, cues: "Clean, then squat. That's one." },
  { id: "kb-snatch-test", name: "Snatch Intervals", equipment: ["kettlebell"], patterns: ["pull", "hinge"], muscles: ["full body"], level: "advanced", bells: 1, timed: true, defaultReps: 30, defaultSets: 5, rest: 30, cues: "Smooth cycling. Switch hands as needed." },
  { id: "kb-halo", name: "Halo", equipment: ["kettlebell"], patterns: ["mobility"], muscles: ["shoulders", "core"], level: "beginner", bells: 1, timed: false, defaultReps: 8, defaultSets: 2, rest: 20, cues: "Circle the bell around the head. Slow and close." },
  { id: "kb-around-the-world", name: "Around the Body Pass", equipment: ["kettlebell"], patterns: ["mobility"], muscles: ["core", "grip"], level: "beginner", bells: 1, timed: false, defaultReps: 10, defaultSets: 2, rest: 20, cues: "Pass the bell around the waist. Hips still." },
  { id: "kb-figure-8", name: "Figure-8", equipment: ["kettlebell"], patterns: ["mobility", "core"], muscles: ["core", "grip"], level: "beginner", bells: 1, timed: false, defaultReps: 10, defaultSets: 2, rest: 20, cues: "Weave the bell through the legs in a figure-8." },

  /* ——— Bodyweight push ——— */
  { id: "bw-pushup", name: "Push-Up", equipment: ["bodyweight"], patterns: ["push"], muscles: ["chest", "triceps", "core"], level: "beginner", bells: 0, timed: false, defaultReps: 12, defaultSets: 3, rest: 45, cues: "Body as one line. Chest to a fist off the floor." },
  { id: "bw-knee-pushup", name: "Knee Push-Up", equipment: ["bodyweight"], patterns: ["push"], muscles: ["chest", "triceps"], level: "beginner", bells: 0, timed: false, defaultReps: 12, defaultSets: 3, rest: 40, cues: "Knees down, still a straight line from head to knees." },
  { id: "bw-decline-pushup", name: "Decline Push-Up", equipment: ["bodyweight"], patterns: ["push"], muscles: ["chest", "shoulders", "triceps"], level: "intermediate", bells: 0, timed: false, defaultReps: 10, defaultSets: 3, rest: 50, cues: "Feet elevated. Don't pike the hips." },
  { id: "bw-diamond-pushup", name: "Diamond Push-Up", equipment: ["bodyweight"], patterns: ["push"], muscles: ["triceps", "chest"], level: "intermediate", bells: 0, timed: false, defaultReps: 8, defaultSets: 3, rest: 50, cues: "Hands under the sternum, thumbs and index fingers touch." },
  { id: "bw-archer-pushup", name: "Archer Push-Up", equipment: ["bodyweight"], patterns: ["push"], muscles: ["chest", "triceps", "shoulders"], level: "advanced", bells: 0, timed: false, defaultReps: 6, defaultSets: 3, rest: 60, cues: "Shift load onto one arm while the other stays long." },
  { id: "bw-pike-pushup", name: "Pike Push-Up", equipment: ["bodyweight"], patterns: ["push"], muscles: ["shoulders", "triceps"], level: "intermediate", bells: 0, timed: false, defaultReps: 8, defaultSets: 3, rest: 50, cues: "Hips high. Head travels between the hands." },
  { id: "bw-handstand-hold", name: "Wall Handstand Hold", equipment: ["bodyweight"], patterns: ["push"], muscles: ["shoulders", "core"], level: "advanced", bells: 0, timed: true, defaultReps: 20, defaultSets: 4, rest: 60, cues: "Belly to wall or back to wall. Ribs in, lock the elbows." },
  { id: "bw-dip", name: "Bench Dip", equipment: ["bodyweight"], patterns: ["push"], muscles: ["triceps", "chest"], level: "beginner", bells: 0, timed: false, defaultReps: 12, defaultSets: 3, rest: 45, cues: "Hands on a bench, lower until elbows ~90°." },

  /* ——— Bodyweight pull / if no bar, rows from table mentioned as inverted ——— */
  { id: "bw-pullup", name: "Pull-Up", equipment: ["bodyweight"], patterns: ["pull"], muscles: ["back", "biceps"], level: "intermediate", bells: 0, timed: false, defaultReps: 6, defaultSets: 4, rest: 90, cues: "From a dead hang, pull chest toward the bar. Needs a bar." },
  { id: "bw-chinup", name: "Chin-Up", equipment: ["bodyweight"], patterns: ["pull"], muscles: ["biceps", "back"], level: "intermediate", bells: 0, timed: false, defaultReps: 6, defaultSets: 4, rest: 90, cues: "Supinated grip. Needs a bar." },
  { id: "bw-inverted-row", name: "Inverted Row", equipment: ["bodyweight"], patterns: ["pull"], muscles: ["back", "biceps"], level: "beginner", bells: 0, timed: false, defaultReps: 10, defaultSets: 3, rest: 45, cues: "Under a table or bar. Body straight, pull the chest up." },
  { id: "bw-scap-hang", name: "Scapular Hang", equipment: ["bodyweight"], patterns: ["pull"], muscles: ["back", "shoulders"], level: "beginner", bells: 0, timed: false, defaultReps: 8, defaultSets: 3, rest: 40, cues: "Dead hang, then depress and retract the scaps. Needs a bar." },

  /* ——— Bodyweight squat / lunge ——— */
  { id: "bw-squat", name: "Bodyweight Squat", equipment: ["bodyweight"], patterns: ["squat"], muscles: ["quads", "glutes"], level: "beginner", bells: 0, timed: false, defaultReps: 15, defaultSets: 3, rest: 40, cues: "Sit between the heels. Chest proud." },
  { id: "bw-pulse-squat", name: "Pulse Squat", equipment: ["bodyweight"], patterns: ["squat"], muscles: ["quads", "glutes"], level: "beginner", bells: 0, timed: false, defaultReps: 20, defaultSets: 3, rest: 40, cues: "Stay in the bottom third and pulse." },
  { id: "bw-split-squat", name: "Split Squat", equipment: ["bodyweight"], patterns: ["lunge"], muscles: ["quads", "glutes"], level: "beginner", bells: 0, timed: false, defaultReps: 10, defaultSets: 3, rest: 40, cues: "Static lunge stance. Drop the back knee." },
  { id: "bw-reverse-lunge", name: "Reverse Lunge", equipment: ["bodyweight"], patterns: ["lunge"], muscles: ["quads", "glutes"], level: "beginner", bells: 0, timed: false, defaultReps: 10, defaultSets: 3, rest: 40, cues: "Step back, then drive through the front heel." },
  { id: "bw-walking-lunge", name: "Walking Lunge", equipment: ["bodyweight"], patterns: ["lunge"], muscles: ["quads", "glutes"], level: "beginner", bells: 0, timed: false, defaultReps: 16, defaultSets: 3, rest: 40, cues: "Long walking steps. Torso tall." },
  { id: "bw-stepup", name: "Step-Up", equipment: ["bodyweight"], patterns: ["lunge"], muscles: ["quads", "glutes"], level: "beginner", bells: 0, timed: false, defaultReps: 10, defaultSets: 3, rest: 40, cues: "Drive through the whole foot on the box. Don't push off the back leg." },
  { id: "bw-pistol", name: "Assisted Pistol Squat", equipment: ["bodyweight"], patterns: ["squat"], muscles: ["quads", "glutes", "core"], level: "advanced", bells: 0, timed: false, defaultReps: 5, defaultSets: 3, rest: 60, cues: "Hold a doorframe or the other foot's toes. Control the descent." },
  { id: "bw-cossack", name: "Cossack Squat", equipment: ["bodyweight"], patterns: ["squat", "mobility"], muscles: ["adductors", "quads"], level: "intermediate", bells: 0, timed: false, defaultReps: 6, defaultSets: 3, rest: 40, cues: "Wide stance, sit into one side." },
  { id: "bw-glute-bridge", name: "Glute Bridge", equipment: ["bodyweight"], patterns: ["hinge"], muscles: ["glutes", "hamstrings"], level: "beginner", bells: 0, timed: false, defaultReps: 15, defaultSets: 3, rest: 30, cues: "Drive through the heels. Squeeze at the top, no overarch." },
  { id: "bw-single-bridge", name: "Single-Leg Bridge", equipment: ["bodyweight"], patterns: ["hinge"], muscles: ["glutes", "hamstrings"], level: "intermediate", bells: 0, timed: false, defaultReps: 10, defaultSets: 3, rest: 40, cues: "One foot planted. Hips stay level." },
  { id: "bw-hip-thrust", name: "Shoulder-Elevated Hip Thrust", equipment: ["bodyweight"], patterns: ["hinge"], muscles: ["glutes"], level: "beginner", bells: 0, timed: false, defaultReps: 12, defaultSets: 3, rest: 40, cues: "Shoulders on a bench or couch. Chin tucked." },

  /* ——— Core / trunk ——— */
  { id: "bw-plank", name: "Plank", equipment: ["bodyweight"], patterns: ["core"], muscles: ["core"], level: "beginner", bells: 0, timed: true, defaultReps: 40, defaultSets: 3, rest: 30, cues: "Ribs down, glutes on. Don't dump into the low back." },
  { id: "bw-side-plank", name: "Side Plank", equipment: ["bodyweight"], patterns: ["core"], muscles: ["obliques"], level: "beginner", bells: 0, timed: true, defaultReps: 25, defaultSets: 3, rest: 30, cues: "Stacked or staggered feet. Hips high." },
  { id: "bw-hollow", name: "Hollow Hold", equipment: ["bodyweight"], patterns: ["core"], muscles: ["core"], level: "intermediate", bells: 0, timed: true, defaultReps: 25, defaultSets: 3, rest: 30, cues: "Low back glued to the floor. Arms and legs long." },
  { id: "bw-dead-bug", name: "Dead Bug", equipment: ["bodyweight"], patterns: ["core"], muscles: ["core"], level: "beginner", bells: 0, timed: false, defaultReps: 8, defaultSets: 3, rest: 30, cues: "Opposite arm and leg reach. Low back stays down." },
  { id: "bw-bird-dog", name: "Bird Dog", equipment: ["bodyweight"], patterns: ["core"], muscles: ["core", "back"], level: "beginner", bells: 0, timed: false, defaultReps: 8, defaultSets: 3, rest: 20, cues: "Reach long, don't rotate the hips." },
  { id: "bw-hanging-knee", name: "Hanging Knee Raise", equipment: ["bodyweight"], patterns: ["core"], muscles: ["core", "hip flexors"], level: "intermediate", bells: 0, timed: false, defaultReps: 8, defaultSets: 3, rest: 45, cues: "Needs a bar. Posterior tilt at the top." },
  { id: "bw-situp", name: "Sit-Up", equipment: ["bodyweight"], patterns: ["core"], muscles: ["core"], level: "beginner", bells: 0, timed: false, defaultReps: 15, defaultSets: 3, rest: 30, cues: "Controlled up and down. Don't yank the neck." },
  { id: "bw-leg-raise", name: "Lying Leg Raise", equipment: ["bodyweight"], patterns: ["core"], muscles: ["core", "hip flexors"], level: "beginner", bells: 0, timed: false, defaultReps: 12, defaultSets: 3, rest: 30, cues: "Press the low back down as the legs lower." },

  /* ——— Conditioning / locomotion ——— */
  { id: "bw-burpee", name: "Burpee", equipment: ["bodyweight"], patterns: ["conditioning"], muscles: ["full body"], level: "intermediate", bells: 0, timed: false, defaultReps: 8, defaultSets: 4, rest: 45, cues: "Squat, plank, push-up optional, jump. Smooth, not sloppy." },
  { id: "bw-mountain", name: "Mountain Climber", equipment: ["bodyweight"], patterns: ["conditioning", "core"], muscles: ["core", "hip flexors"], level: "beginner", bells: 0, timed: true, defaultReps: 30, defaultSets: 3, rest: 30, cues: "Plank position. Drive knees without bouncing the hips." },
  { id: "bw-jump-squat", name: "Jump Squat", equipment: ["bodyweight"], patterns: ["conditioning", "squat"], muscles: ["quads", "glutes"], level: "intermediate", bells: 0, timed: false, defaultReps: 10, defaultSets: 3, rest: 45, cues: "Soft landing, full foot. Don't let the knees cave." },
  { id: "bw-skater", name: "Skater Bound", equipment: ["bodyweight"], patterns: ["conditioning"], muscles: ["glutes", "legs"], level: "intermediate", bells: 0, timed: false, defaultReps: 12, defaultSets: 3, rest: 40, cues: "Side to side, stick the landing for a beat." },
  { id: "bw-high-knees", name: "High Knees", equipment: ["bodyweight"], patterns: ["conditioning"], muscles: ["hip flexors", "calves"], level: "beginner", bells: 0, timed: true, defaultReps: 20, defaultSets: 3, rest: 25, cues: "Tall posture, quick rhythm." },
  { id: "bw-jumping-jack", name: "Jumping Jack", equipment: ["bodyweight"], patterns: ["conditioning"], muscles: ["full body"], level: "beginner", bells: 0, timed: true, defaultReps: 30, defaultSets: 3, rest: 20, cues: "Easy cadence. Soft knees." },
  { id: "bw-bear-crawl", name: "Bear Crawl", equipment: ["bodyweight"], patterns: ["locomotion", "core"], muscles: ["core", "shoulders"], level: "intermediate", bells: 0, timed: true, defaultReps: 30, defaultSets: 3, rest: 40, cues: "Knees hover an inch. Opposite hand and foot." },
  { id: "bw-crab-walk", name: "Crab Walk", equipment: ["bodyweight"], patterns: ["locomotion"], muscles: ["shoulders", "glutes"], level: "beginner", bells: 0, timed: true, defaultReps: 20, defaultSets: 2, rest: 30, cues: "Hips up. Don't let them sag." },
  { id: "bw-inchworm", name: "Inchworm", equipment: ["bodyweight"], patterns: ["mobility", "core"], muscles: ["hamstrings", "core", "shoulders"], level: "beginner", bells: 0, timed: false, defaultReps: 6, defaultSets: 2, rest: 20, cues: "Walk the hands out to plank, walk the feet in." },

  /* ——— Mobility / warmup ——— */
  { id: "bw-world-greatest", name: "World's Greatest Stretch", equipment: ["bodyweight"], patterns: ["mobility"], muscles: ["hips", "t-spine"], level: "beginner", bells: 0, timed: false, defaultReps: 5, defaultSets: 2, rest: 15, cues: "Lunge, elbow toward the instep, then rotate the chest open." },
  { id: "bw-hip-opener", name: "90/90 Hip Switch", equipment: ["bodyweight"], patterns: ["mobility"], muscles: ["hips"], level: "beginner", bells: 0, timed: false, defaultReps: 8, defaultSets: 2, rest: 15, cues: "Both knees at 90°. Switch sides without using the hands if you can." },
  { id: "bw-cat-cow", name: "Cat-Cow", equipment: ["bodyweight"], patterns: ["mobility"], muscles: ["spine"], level: "beginner", bells: 0, timed: false, defaultReps: 8, defaultSets: 2, rest: 10, cues: "Slow spinal waves. Breathe with each shape." },
  { id: "bw-thoracic-rot", name: "Open Book", equipment: ["bodyweight"], patterns: ["mobility"], muscles: ["t-spine"], level: "beginner", bells: 0, timed: false, defaultReps: 6, defaultSets: 2, rest: 15, cues: "Sidelying, knees stacked. Rotate the top arm and chest." },
  { id: "bw-down-dog", name: "Downward Dog", equipment: ["bodyweight"], patterns: ["mobility"], muscles: ["hamstrings", "shoulders"], level: "beginner", bells: 0, timed: true, defaultReps: 30, defaultSets: 2, rest: 15, cues: "Push the floor away. Soft knees if hamstrings are loud." },
  { id: "bw-couch-stretch", name: "Couch Stretch", equipment: ["bodyweight"], patterns: ["mobility"], muscles: ["hip flexors", "quads"], level: "beginner", bells: 0, timed: true, defaultReps: 30, defaultSets: 2, rest: 10, cues: "Rear shin up a wall or couch. Squeeze the glute of that leg." },
  { id: "bw-child", name: "Child's Pose", equipment: ["bodyweight"], patterns: ["mobility"], muscles: ["back", "hips"], level: "beginner", bells: 0, timed: true, defaultReps: 30, defaultSets: 1, rest: 0, cues: "Hips to heels, arms long. Breathe into the back." }
];
